export const buildingSystems = [
  {
    id: 'chiller-plant',
    icon: '❄️',
    title: 'Chiller Plant',
    subtitle: 'Cooling Production',
    description: 'Chillers, chilled water pumps, condenser water pumps, cooling towers, VFDs, expansion tanks, heat exchangers, BAS points, alarms, and operating sequences.',
    status: 'Foundation Ready',
    equipmentCount: 9,
  },
  {
    id: 'boiler-plant',
    icon: '🔥',
    title: 'Boiler Plant',
    subtitle: 'Heating / Steam',
    description: 'Boilers, burners, feedwater, condensate, steam traps, PRVs, safeties, pumps, expansion, controls, and heating operation.',
    status: 'Coming Next',
    equipmentCount: 10,
  },
  {
    id: 'airside',
    icon: '🌬️',
    title: 'Airside Systems',
    subtitle: 'Ventilation / Comfort',
    description: 'AHUs, VAV boxes, dampers, filters, coils, supply fans, return fans, economizers, and space comfort troubleshooting.',
    status: 'Coming Soon',
    equipmentCount: 8,
  },
  {
    id: 'electrical',
    icon: '⚡',
    title: 'Electrical Distribution',
    subtitle: 'Power / Motor Control',
    description: 'Switchgear, transformers, panels, MCCs, VFDs, ATS, generators, breakers, starters, and power troubleshooting.',
    status: 'Coming Soon',
    equipmentCount: 11,
  },
  {
    id: 'domestic-water',
    icon: '🚰',
    title: 'Domestic Water',
    subtitle: 'Plumbing Systems',
    description: 'Booster pumps, water heaters, PRVs, backflow preventers, tanks, mixing valves, recirculation, and pressure control.',
    status: 'Coming Soon',
    equipmentCount: 7,
  },
  {
    id: 'fire-protection',
    icon: '🚒',
    title: 'Fire Protection',
    subtitle: 'Life Safety',
    description: 'Fire pumps, standpipes, sprinkler systems, alarm valves, jockey pumps, inspection workflows, and fire protection basics.',
    status: 'Coming Soon',
    equipmentCount: 7,
  },
]

export const chillerPlantEquipment = [
  { id: 'chillers', name: 'Water-Cooled Chillers', type: 'Cooling Production', points: ['CHWS', 'CHWR', 'Tons', 'Amps', 'Flow Proof'] },
  { id: 'chw-pumps', name: 'Chilled Water Pumps', type: 'Building Loop', points: ['Pump Status', 'VFD Speed', 'DP', 'Flow'] },
  { id: 'cw-pumps', name: 'Condenser Water Pumps', type: 'Condenser Loop', points: ['Pump Status', 'Speed', 'Flow', 'DP'] },
  { id: 'cooling-towers', name: 'Cooling Towers', type: 'Heat Rejection', points: ['Fan Speed', 'Basin Level', 'CWS Temp', 'Approach'] },
  { id: 'vfds', name: 'VFDs', type: 'Motor Control', points: ['Command', 'Speed', 'Fault', 'Amps'] },
  { id: 'expansion-tank', name: 'Expansion Tank', type: 'Pressure Control', points: ['System Pressure', 'Fill Status'] },
  { id: 'plate-hx', name: 'Plate Heat Exchanger', type: 'Heat Transfer', points: ['EWT', 'LWT', 'DP', 'Valve Status'] },
]
