export const buildingSystems = [
  {
    id: 'chiller-plant',
    icon: '❄️',
    title: 'Chiller Plant',
    subtitle: 'Cooling Production',
    description: 'Chillers, chilled water pumps, condenser water pumps, cooling towers, VFDs, expansion tanks, heat exchangers, BAS points, alarms, and operating sequences.',
    status: 'Active',
    equipmentCount: 9,
  },
  {
    id: 'boiler-plant',
    icon: '🔥',
    title: 'Boiler Plant',
    subtitle: 'Heating / Steam',
    description: 'Boilers, burners, feedwater, condensate, steam traps, PRVs, safeties, pumps, expansion, controls, and heating operation.',
    status: 'Coming Next',
    equipmentCount: 10,
  },
  {
    id: 'airside',
    icon: '🌬️',
    title: 'Airside Systems',
    subtitle: 'Ventilation / Comfort',
    description: 'AHUs, VAV boxes, dampers, filters, coils, supply fans, return fans, economizers, and space comfort troubleshooting.',
    status: 'Coming Soon',
    equipmentCount: 8,
  },
  {
    id: 'electrical',
    icon: '⚡',
    title: 'Electrical Distribution',
    subtitle: 'Power / Motor Control',
    description: 'Switchgear, transformers, panels, MCCs, VFDs, ATS, generators, breakers, starters, and power troubleshooting.',
    status: 'Coming Soon',
    equipmentCount: 11,
  },
  {
    id: 'domestic-water',
    icon: '🚰',
    title: 'Domestic Water',
    subtitle: 'Plumbing Systems',
    description: 'Booster pumps, water heaters, PRVs, backflow preventers, tanks, mixing valves, recirculation, and pressure control.',
    status: 'Coming Soon',
    equipmentCount: 7,
  },
  {
    id: 'fire-protection',
    icon: '🚒',
    title: 'Fire Protection',
    subtitle: 'Life Safety',
    description: 'Fire pumps, standpipes, sprinkler systems, alarm valves, jockey pumps, inspection workflows, and fire protection basics.',
    status: 'Coming Soon',
    equipmentCount: 7,
  },
]

export const chillerPlantEquipment = [
  {
    id: 'chillers',
    name: 'Water-Cooled Chillers',
    type: 'Cooling Production',
    icon: '❄️',
    description: 'Removes heat from chilled water and rejects it into the condenser water loop.',
    sequence: 'Flow must be proven before the chiller starts. Once enabled, the compressor loads to maintain chilled water supply temperature.',
    specs: { Status: 'Running', CHWS: '44°F', Load: '46%', Amps: '62%' },
    points: ['CHWS', 'CHWR', 'Tons', 'Amps', 'Flow Proof', 'Oil Pressure', 'Condenser Approach'],
    components: [
      { name: 'Compressor', function: 'Raises refrigerant pressure and temperature so heat can be rejected in the condenser.', failure: 'High amps, surge, oil issues, failure to load.' },
      { name: 'Evaporator', function: 'Transfers heat from chilled water into refrigerant.', failure: 'Low flow, poor approach, freezing risk, tube fouling.' },
      { name: 'Condenser', function: 'Rejects refrigerant heat into condenser water.', failure: 'High head pressure, dirty tubes, poor tower performance.' },
      { name: 'Expansion Device', function: 'Drops refrigerant pressure before the evaporator.', failure: 'Starved evaporator, unstable superheat, low capacity.' },
      { name: 'Oil System', function: 'Lubricates compressor bearings and moving parts.', failure: 'Low oil pressure, high oil temperature, shutdown.' },
      { name: 'Control Panel', function: 'Manages safeties, staging, alarms, and operating limits.', failure: 'Fault lockouts, sensor issues, failed commands.' },
    ],
  },
  {
    id: 'chw-pumps',
    name: 'Chilled Water Pumps',
    type: 'Building Loop',
    icon: '🌀',
    description: 'Moves chilled water from the central plant to building coils and air handlers.',
    sequence: 'Lead pump starts first. VFD speed modulates to maintain differential pressure as valves open and close.',
    specs: { Status: 'Running', Speed: '52%', DP: '22 PSI', Flow: 'Normal' },
    points: ['Pump Status', 'VFD Speed', 'Differential Pressure', 'Flow', 'Start Command', 'Fault'],
    components: [
      { name: 'Motor', function: 'Converts electrical power into shaft rotation.', failure: 'High amps, overheating, bearing noise, failed start.' },
      { name: 'VFD', function: 'Controls pump speed based on pressure demand.', failure: 'Drive fault, speed hunting, no output, overcurrent.' },
      { name: 'Coupling', function: 'Connects motor shaft to pump shaft.', failure: 'Misalignment, vibration, worn insert, coupling failure.' },
      { name: 'Impeller', function: 'Adds energy to water and creates flow.', failure: 'Worn impeller, cavitation damage, low flow.' },
      { name: 'Mechanical Seal', function: 'Prevents water from leaking around the shaft.', failure: 'Dripping, overheating, dry-run damage.' },
      { name: 'Bearings', function: 'Support the rotating shaft.', failure: 'Noise, heat, vibration, bearing failure.' },
    ],
  },
  {
    id: 'cw-pumps',
    name: 'Condenser Water Pumps',
    type: 'Condenser Loop',
    icon: '🌊',
    description: 'Moves condenser water between chillers and cooling towers for heat rejection.',
    sequence: 'Condenser water pump starts before chiller enable. Flow must be proven to allow chiller operation.',
    specs: { Status: 'Running', Speed: '58%', DP: '18 PSI', Flow: 'Normal' },
    points: ['Pump Status', 'Speed', 'Flow', 'DP', 'Start Command', 'Proof'],
    components: [
      { name: 'Motor', function: 'Provides rotation for the pump.', failure: 'High amps, overload, heat.' },
      { name: 'Pump Casing', function: 'Directs water through the pump.', failure: 'Leaks, erosion, damaged casing.' },
      { name: 'Impeller', function: 'Creates water flow.', failure: 'Cavitation, wear, low performance.' },
      { name: 'Seal', function: 'Prevents shaft leakage.', failure: 'Water leakage, seal face damage.' },
      { name: 'VFD', function: 'Modulates flow or pressure.', failure: 'Drive trip, unstable speed.' },
    ],
  },
  {
    id: 'cooling-towers',
    name: 'Cooling Towers',
    type: 'Heat Rejection',
    icon: '🗼',
    description: 'Rejects heat from condenser water to the outdoor air using evaporation and airflow.',
    sequence: 'Tower fans stage or modulate to maintain condenser water supply temperature.',
    specs: { Status: 'Auto', Fan: '45%', Basin: 'Normal', Approach: '7°F' },
    points: ['Fan Speed', 'Basin Level', 'CWS Temp', 'CWR Temp', 'Approach', 'Vibration'],
    components: [
      { name: 'Fan', function: 'Moves air through the tower.', failure: 'Vibration, belt failure, motor overload.' },
      { name: 'Gearbox', function: 'Transfers motor power to the fan at the proper speed.', failure: 'Oil leaks, noise, overheating.' },
      { name: 'Fill Media', function: 'Increases water/air contact surface area.', failure: 'Scaling, biological growth, blockage.' },
      { name: 'Spray Nozzles', function: 'Distribute water over fill.', failure: 'Clogged nozzles, poor distribution.' },
      { name: 'Cold Water Basin', function: 'Collects cooled water.', failure: 'Low level, debris, overflow.' },
      { name: 'Makeup Valve', function: 'Adds water to replace losses.', failure: 'Stuck closed/open, low basin level.' },
    ],
  },
  {
    id: 'vfds',
    name: 'VFDs',
    type: 'Motor Control',
    icon: '⚡',
    description: 'Controls motor speed for pumps, fans, and other rotating equipment.',
    sequence: 'BAS sends a speed command. The VFD ramps the motor and reports speed, current, and fault status.',
    specs: { Status: 'Auto', Speed: '52%', Amps: 'Normal', Fault: 'None' },
    points: ['Command', 'Speed Feedback', 'Fault', 'Amps', 'Hand/Auto', 'Run Status'],
    components: [
      { name: 'Keypad', function: 'Local display and control interface.', failure: 'Display failure, locked settings.' },
      { name: 'DC Bus', function: 'Stores rectified power inside the drive.', failure: 'Overvoltage, capacitor failure.' },
      { name: 'IGBTs', function: 'Switch output power to control motor frequency.', failure: 'Output fault, drive trip.' },
      { name: 'Cooling Fan', function: 'Removes heat from drive electronics.', failure: 'Overtemperature trip.' },
      { name: 'Control Board', function: 'Processes commands and feedback.', failure: 'Communication fault.' },
    ],
  },
  {
    id: 'expansion-tank',
    name: 'Expansion Tank',
    type: 'Pressure Control',
    icon: '⚪',
    description: 'Absorbs water expansion and stabilizes pressure in the closed hydronic loop.',
    sequence: 'The tank remains connected to the system and absorbs pressure changes as water temperature changes.',
    specs: { Status: 'Normal', Pressure: '18 PSI', Charge: '12 PSI', Isolation: 'Open' },
    points: ['System Pressure', 'Fill Status', 'Low Pressure Alarm'],
    components: [
      { name: 'Steel Shell', function: 'Outer body that contains pressure.', failure: 'Corrosion, leaks.' },
      { name: 'Bladder', function: 'Separates system water from air charge.', failure: 'Waterlogged tank, pressure swings.' },
      { name: 'Air Charge', function: 'Provides cushion for expansion.', failure: 'Incorrect charge pressure.' },
      { name: 'Isolation Valve', function: 'Allows tank service.', failure: 'Accidentally closed valve.' },
      { name: 'Pressure Gauge', function: 'Displays pressure.', failure: 'Bad reading.' },
    ],
  },
  {
    id: 'plate-hx',
    name: 'Plate Heat Exchanger',
    type: 'Heat Transfer',
    icon: '🔁',
    description: 'Transfers heat between loops while keeping fluids separated.',
    sequence: 'Control valves modulate flow through the heat exchanger to maintain leaving water temperature.',
    specs: { Status: 'Available', Approach: '4°F', DP: '8 PSI', Valves: 'Open' },
    points: ['Entering Temp', 'Leaving Temp', 'DP', 'Valve Status'],
    components: [
      { name: 'Plates', function: 'Thin surfaces that transfer heat.', failure: 'Fouling, scaling, blocked passages.' },
      { name: 'Gaskets', function: 'Seal fluid channels.', failure: 'Leaks, cross-contamination.' },
      { name: 'Frame', function: 'Holds plate pack together.', failure: 'Loose compression, frame damage.' },
      { name: 'Tie Rods', function: 'Compress the plate pack.', failure: 'Improper compression.' },
      { name: 'Inlets/Outlets', function: 'Route hot and cold fluids.', failure: 'Valve misposition, blockage.' },
    ],
  },
]
